name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        dotnet: [ '3.0.100-preview9-014004' ]
        config: [ Debug, Release ]
        
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet build -c ${{ matrix.config }}
      - run: dotnet test
      - run: dotnet pack
